[workspace]
authors = ["Sierra Arn"]
channels = ["conda-forge"]
name = "geo-recsys-simple-lib"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = ">=3.13.3,<3.14"
scikit-learn = ">=1.7.0,<2"
pandas = ">=2.3.0,<3"
numpy = ">=2.3.1,<3"
pydantic = ">=2.11.7,<3"
huggingface_hub = ">=0.33.1,<0.34"

[environments]
test = ["test"]
dev = ["dev"]

[feature.test.dependencies]
pytest-cov = "*"

[feature.test.tasks]
test = { cmd = "pytest tests/ --cov=src --cov-report=term-missing -W ignore::DeprecationWarning" }

[feature.dev.pypi-dependencies]
build = "*"

[feature.dev.tasks]
build = { cmd = "python -m build" }
